name: Daily IPO Scraper

on:
  schedule:
    - cron: "0 5 * * *"  # every day 9 AM UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug working dir
        run: |
              pwd
              ls -R
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml
      - name: Run scraper and email
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python scraper_mail.py
